name: flutter_fin_pwa
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase (these are known to work)
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4

  # State Management
  provider: ^6.1.1

  # UI & Utilities
  image_picker: ^1.0.7
  fl_chart: ^0.66.2
  intl: ^0.19.0 

  cupertino_icons: ^1.0.2
  collection: ^1.19.1
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
