// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWZzovMjao9zr_2iTJWWTn2v-c-dkF5S8',
    appId: '1:995036170138:web:1be84e9da3d996336e9c23',
    messagingSenderId: '995036170138',
    projectId: 'personal-io-system',
    authDomain: 'personal-io-system.firebaseapp.com',
    storageBucket: 'personal-io-system.firebasestorage.app',
    measurementId: 'G-GHL6FPN11Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH7o-dRtvQgfBYyDj9p2icLMtmB23m6aY',
    appId: '1:995036170138:android:27d86de7a1d7e1d06e9c23',
    messagingSenderId: '995036170138',
    projectId: 'personal-io-system',
    storageBucket: 'personal-io-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKhFB6H8l8aLCwFAq87FlruesGuya9jQQ',
    appId: '1:995036170138:ios:2c17205eb9304fdb6e9c23',
    messagingSenderId: '995036170138',
    projectId: 'personal-io-system',
    storageBucket: 'personal-io-system.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinPwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKhFB6H8l8aLCwFAq87FlruesGuya9jQQ',
    appId: '1:995036170138:ios:2c17205eb9304fdb6e9c23',
    messagingSenderId: '995036170138',
    projectId: 'personal-io-system',
    storageBucket: 'personal-io-system.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinPwa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWZzovMjao9zr_2iTJWWTn2v-c-dkF5S8',
    appId: '1:995036170138:web:1be84e9da3d996336e9c23',
    messagingSenderId: '995036170138',
    projectId: 'personal-io-system',
    authDomain: 'personal-io-system.firebaseapp.com',
    storageBucket: 'personal-io-system.firebasestorage.app',
    measurementId: 'G-GHL6FPN11Z',
  );

}